-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgn8pgU7/6lqlGAbdu
xZe+cz6unO5kqfNU8dQDBnJlIEegCgYIKoZIzj0DAQehRANCAATzCLGwEAuj0+qW
pXH+eHxsdJicjVPDKR/XWcT/BrEac1Ydb4CRFJPm/tsdln54nZdz1xxD95a2iKYO
53E2Z95Z
-----END PRIVATE KEY-----